ALTER TABLE category ADD COLUMN IF NOT EXISTS title VARCHAR DEFAULT NULL;
ALTER TABLE category ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL;
ALTER TABLE category ADD COLUMN IF NOT EXISTS article_info TEXT DEFAULT NULL;
ALTER TABLE category ADD COLUMN IF NOT EXISTS remarks TEXT DEFAULT NULL;

DROP TABLE IF EXISTS category_info;